# ==============================================================================
# Configurações Globais / Comuns a Todos os Ambientes (DES, TES, PROD)
# ==============================================================================

# Identificação da Aplicação
spring.application.name=demo

# Profile padrão quando não fornecido via SPRING_PROFILES_ACTIVE ou -Dspring.profiles.active
spring.profiles.default=des

# Porta HTTP do Servidor Web
server.port=${PORT:8080}

# Gerenciamento de Sessão JPA / Hibernate
spring.jpa.open-in-view=false

# Serialização JSON (Jackson)
spring.jackson.default-property-inclusion=non_null
spring.jackson.deserialization.fail-on-unknown-properties=false
